# Variables that could be use to replace values in TOML file to make it more flexilble
# literal such as String, Integer, Float, Boolean could be replace without too much overhead
#
# wip on toml table and arrays
replicas = 1

image_name = "nginx"
# should be referenced as "$[arr::typed" -> typed use replace the entire section including the quotes 
map = ["default_configmap"]
from = { type = "map", name = "foo", item = "lol" }