# a daemonset
kind = "workload::daemonset"
name = "rusty"
metadata = { name = "nodejs", tier = "monitoring" }

# container name rust
[workload]
    # only schedule on node which has NoSchedule taint
    tolerations = [
        { key = "node-role.kubernetes.io/master", effect = "NoSchedule" }
    ]

    [workload.nodejs]
    image = "k8s.gcr.io/echoserver"
    tag = "1.4"
    policy = "IfNotPresent"