# a deployment
kind = "workload::deployment"
name = "nginx"
metadata = { name = "nginx", tier = "backend" }
namespace = "bar"

# container name nginx
[workload]
    replicas = "$[replicas]"

    [workload.nginx]
    image = "$[image_name]"
    tag = "1.19.10"
    policy = "IfNotPresent"

        # env from
        [workload.nginx.env_from]
        map = "$[map::typed]"
        secret = [
            "nginx-secret"
        ]

        # env
        [workload.nginx.env]
        from = [
            "$[from::typed]",
            { type = "res_field", name = "nginx-container", item = "limits.cpu" }
        ]
    
        raw = [
            { name = "A_VALUE", item = "bar" }
        ]