# a deployment
kind = "workload::deployment"
name = "rusty"
metadata = { name = "rusty", tier = "backend" }

# container name rust
[workload]
    replicas = "$[replicas]"

    [workload.rust]
    image = "$[image_provider]/$[image_name]"
    tag = "bar"
    policy = "IfNotPresent"

        # env from
        [workload.rust.env_from]
        map = "$[map::typed]"
        secret = [
            "default_secret"
        ]

        # env
        [workload.rust.env]
        from = [
            "$[from::typed]",
            { type = "res_field", name = "rust-container", item = "limits.cpu" }
        ]
        raw = [
            { name = "A_VALUE", item = "bar" }
        ]