kind = "network::ingress"
name = "nginx"
metadata = { name = "nginx", tier = "ingress" }
namespace = "bar"

[ingress]

    # ingress.default is a reserved keyword
    [ingress.default]
        backend = { name = "nginx", port = 80 }

    [ingress.rules]

        [ingress.rules.nginx]
            host = "foo.bar.com"

            [ingress.rules.nginx.paths]

                [ingress.rules.nginx.paths.0]
                    type = "Prefix"
                    path = "/"
                    backend = { name = "nginx", port = 80 }