kind = "env::secret"
name = "nginx-secret"
metadata = { name = "nginx-secret", tier = "backend" }
namespace = "bar"

[spec]
    [data]
        foo = "bbtea"
        lol = """
            bobba=10
        """