# a service
# a network file could be of type network::service / network::ingress
kind = "network::service"
version = "v1"
name = "rusty"
metadata = { name = "rusty", tier = "backend" }

[annotations]
"external-dns.alpha.kubernetes.io/hostname" = "rusty.dev.org."

[service]
    type = "nodeport"

    [service.ports]

        [service.ports.http]
            protocol = "TCP"
            port = 80
            target_port = 90