# a service
# a network file could be of type network::service / network::ingress
kind = "network::service"
name = "nginx"
metadata = { name = "nginx", tier = "backend" }
namespace = "bar"

[annotations]
"external-dns.alpha.kubernetes.io/hostname" = "nginx.dev.org."

[service]
    type = "NodePort"

    [service.ports]

        [service.ports.http]
            protocol = "TCP"
            port = 80
            target_port = 80