# a service
# a network file could be of type network::service / network::ingress
kind = "network::service"
name = "rusty"
metadata = { name = "rusty", tier = "backend" }

[service]
    type = "nodeport"

    [service.ports]

        [service.ports.http]
            protocol = "TCP"
            port = 80
            target_port = 90