# a statefulset
kind = "workload::statefulset"
name = "nginxst"
metadata = { name = "nginxst", tier = "backend" }
namespace = "bar"

[volume_claims]
    [volume_claims.nginx]
        access_modes = ["ReadWriteOnce"]
        resources_request = [
            { key_name = "storage", value = "1Gi" }
        ]
  
# container name nginx
[workload]
    replicas = 1
          
    [workload.nginx]
    image = "$[image_name]"
    tag = "1.19.10"
    policy = "IfNotPresent"
    # name must match the table of the volume_claims
    volume_mounts = [
        { name = "nginx", mount_path = "/var/log" }
    ]

        # env from
        [workload.nginx.env_from]
        map = [
            "nginx-configmap"
        ]
        secret = [
            "nginx-secret"
        ]

        # env
        [workload.nginx.env]
        raw = [
            { name = "A_VALUE", item = "bar" }
        ]