kind = "Kubernetes"
type = "Deployment"

[variables]
name = "NodeJS"
tag  = "v1.12.0"
port = "80"

[labels]
tier = "backend"
app  = "node"

[spec]
replicas = 1

    [spec.containers]
        
        [spec.containers.node]
        name = "$name"
        image = "node:$tag"
        ports = [
            { name = "http", value = "$port" }
        ]
        config_map = [
            # will make reference to a set of environment variables 
            "misc",
            "api"
        ]
        secrets = [
            # will make a reference to a set of secrets variables
            "salesforce"
        ]
        probes = [
            { liveness = { kind = "exec", command = ["cat", "/tmp/healthy"] } },
            # if a value is a string with a $ we will search for the reference variables
            # { readiness = "$probes.readiness" },
            { readiness = { kind = "http", path = "foo", port = 8080 } }
        ]
