kind = "patch"

[variables]
initialDelaySeconds = 5

[spec]

    [spec.liveness]
    use = "global"

    [spec.readiness]
    kind = "exec"
    command = [
        "cat",
        "/tmp/healthy"
    ]
