name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: AbsaOSS/k3d-action@v1.4.0
      name: "Create single cluster"
      with:
        cluster-name: "ramen"
        args: --agents 1
    - name: Build
      run: cargo build --verbose
    - name: Generate spec from the examples folder
      run: cargo run maomao generate -p examples -o ./out
    - name: Install kubernetes yaml spec from the out folder
      working-directory: out
      run: |
        kubectl create ns bar
        kubectl apply -f .
    - name: Run tests
      run: cargo test --verbose
